apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-otel-agent
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-dev
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.151.0x
      helm:
        releaseName: dev-otel
        valueFiles:
          - $gitea-values/apps/opentelemetry/agent/base-agent.yaml
          - $gitea-values/apps/opentelemetry/agent/dev-values.yaml
    - repoURL: https://github.com/mcheng-splunk/k8s-infrastructure-gitops.git
      targetRevision: main
      ref: gitea-values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true