---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    webhook-url: AgAFvPG233xn+qOage0Jj/uKyYpJRvdcW5JI1sVxlhA1GBKIfA5M9xhWCxV9TK1FeV9XitlWUhcf0TxKHPhhc/SaXK6cmun+cHGrWIePc0JVIj2BpC5KFQjkvN9Q9EXJd7kIu7T3NAPjfjBt/LVFfg19Fa7qxcKQZWrLMGAMmjLb6iPWhszofWQOf5IOD4jf2CfAZNzsiObPJgJzb7Plis8rDp1tcUxi7pD+KAuHEy/HZC/0K2aPly2sNXHXN6sM6VSKRjPeuM3eV6p35sR5E3OA7DzoXnIScpqyVSL8prnAccyH5TuZdr5cVRi05fSD5h0E8e1CBvVx/xL8cOaKtFKq2ofPPV6rvuEPa1LyXAMVwNJ49sVbWfqiFYG2aSXEDbxaOBmpa8fZzo8qUAmqaol1gq9pH11vIdomB/Ap+LAzwDB0On0Woe0jO6fGStswo7Hnl3E81BQ1LMBolBs+rtnYxEQCy/XYJC6sPRNsH+KEj9F1jX8fakU2GoAK032KeJiMC6+lKx59I4TOHGUHTOAx6eZPLz4keCm70+aNoYVJKdOB1fZCV20AnjIGZPXNwtdDaKNtlbRkweHWaR/6Qohv2Xe+42Zbf9yQG/4U2N1g54beFLvXIyXFydqVBGFUhqAWNjEYtomwfU42jAxb9RycnmYkRQ1IYpbIdLFPXi4i+Vue9lLtsWHrwUFWMTeb0hk1Ke5dpnYRA7P2Fuse2fhb5HHlewb77GbgEMKNRAFdo8RUXdAM5wy+98JxnvqyFD3e66Sn9KwpuB935Rtr30c3abtljRixyw6BA+F201cpK+g=
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
