---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    webhook-url: AgBnxdINQhXG5yhCWfQ7YDgPR8ZBS978T0+556t+CYc3MPT7ZhQsFpKofUHkoygSYnJZtSPYxMHwPMcPMQBHXFKNVrL14AlPio1yWr/JRYt++XfJzPK48E5okiJoR+7SbeLIRJ4Qtp/mEojQzbm/fRqR4XZDcibvxiC4CFvvSjn/bkEQqWeHuiJAkh6FFRJN6wuNNn3fI6vsCLdtbw6Ey9EHPpoPkPfjCqaUUcuaG++CS/Fxzu/xQuThAuB300kTJwVVsXSBjSXuRQnPk7B9m+GPMFZ4l+HjPgyfTSnjxIsbgXjDFNkyLFy+Fk1K9JB84R4a30brBgJQtnYypM2gHrTvKLnj5/yWU9RM992v5Rl1yDnCJqdAKtxEJ03rrs96wxsw6Cgdn5GRwRhREdsp4N5KQEMJCWjZqzKKkx2EQqwXQ781EFal1LgwdJXwW6mbVBaaixYQ7IdsWk5wwq792ZRE7fcL/OkdCzFRGyv4P9+aVzSx3KWb/2zlBTYgl/7efDYrWnum8gKc3JK3tK2bUcoNLAar9Hn+2N3lDn/VYOK+oYDVzUdVcWMo6Rwqm3voBc+UcSVXQXl3BH+PvnvRM6V0ncWEGcjadc6P/DPPq6+ty3WSt3rsjqWGE4u6A/OKDWJZYAbKmPKNZZn2vyPa61ceGKBDJkncgd9fF7UhFYu/SGnbdaTrlJTAA6nThZ4hukCo+7IHhxgSz/LTFVdgHiUhlu06J0KJisxf0G8fT5fyP+1ellHTZfMQYuaUtK1V/7G23ocKMO34ckaENaLzxphc+ObO8qDciKAGgpsj2K1lubw=
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
