replicaCount: 1

config:
  processors:
    memory_limiter:
      check_interval: 500ms
      limit_percentage: 85
      spike_limit_percentage: 15
    batch:
      send_batch_size: 8192
      send_batch_max_size: 10240

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

autoscaler:
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilization: 50
  targetMemoryUtilization: 60
