replicaCount: 4

config:
  processors:
    memory_limiter:
      check_interval: 500ms
      limit_percentage: 85
      spike_limit_percentage: 15
    batch:
      send_batch_size: 8192
      send_batch_max_size: 10240

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 2Gi

hpa:
  enabled: true
  minReplicas: 4
  maxReplicas: 12
  targetCPUUtilizationPercentage: 80